### ISSUE TITLE
Heroku and final changes

### ISSUE THREAD

**Issue by AndresPitta** [UBC-MDS/DSCI_532_Group_113_Overdose#27]
Hey guys,

I think we need to make a new description in the readme file since we have the new app 'up and running'. 

Also I did a demo for the heroku with my forked repo. Please, give it a look here : (https://overdash-demo.herokuapp.com/). That is not the official one, we still need to create a branch and put that branch in heroku,

**Comment by HanyingZhang** [comment]
Checked the demo and ready to deploy!
